//
//  VTAPIConstants.h
//  LifeStream
//
//  Created by Vasily Timofeev on 08.05.2018.
//  Copyright © 2018 Vasily Timofeev. All rights reserved.
//

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString *const GET_SERVER_API_KEY;

//requests
FOUNDATION_EXPORT NSString *const GET_SERVER_REQUEST_MOVIES_DISCOVER;
FOUNDATION_EXPORT NSString *const GET_SERVER_REQUEST_MOVIE_SMALL_POSTER;
FOUNDATION_EXPORT NSString *const GET_SERVER_REQUEST_MOVIE_BIG_POSTER;


//fields request
FOUNDATION_EXPORT NSString *const SERVER_REQUEST_API_KEY_FIELD_NAME;
FOUNDATION_EXPORT NSString *const SERVER_REQUEST_LANGUAGE_FIELD_NAME;
FOUNDATION_EXPORT NSString *const SERVER_REQUEST_SORT_BY_FIELD_NAME;
FOUNDATION_EXPORT NSString *const SERVER_REQUEST_PAGE_FIELD_NAME;

FOUNDATION_EXPORT NSString *const SERVER_REQUEST_API_KEY_FIELD_VALUE;
FOUNDATION_EXPORT NSString *const SERVER_REQUEST_LANGUAGE_FIELD_VALUE;
FOUNDATION_EXPORT NSString *const SERVER_REQUEST_SORT_BY_FIELD_VALUE;

//fields response
FOUNDATION_EXPORT NSString *const SERVER_RESPONSE_RESULTS_FIELD_NAME;
FOUNDATION_EXPORT NSString *const SERVER_RESPONSE_TOTAL_PAGES_FIELD_NAME;
FOUNDATION_EXPORT NSString *const SERVER_RESPONSE_MOVIE_TITLE_FIELD_NAME;
FOUNDATION_EXPORT NSString *const SERVER_RESPONSE_MOVIE_OVERVIEW_FIELD_NAME;
FOUNDATION_EXPORT NSString *const SERVER_RESPONSE_MOVIE_POSTER_PATH_FIELD_NAME;
